//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("UserAccountsModel", "UserPermission", "Application", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UserAccountsModel.Application), "User", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(UserAccountsModel.User))]

// Original file name:
// Generation date: 4/8/2010 2:39:54 PM
namespace UserAccountsModel
{
    
    /// <summary>
    /// There are no comments for UserAccountsEntities in the schema.
    /// </summary>
    public partial class UserAccountsEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new UserAccountsEntities object using the connection string found in the 'UserAccountsEntities' section of the application configuration file.
        /// </summary>
        public UserAccountsEntities() : 
                base("name=UserAccountsEntities", "UserAccountsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UserAccountsEntities object.
        /// </summary>
        public UserAccountsEntities(string connectionString) : 
                base(connectionString, "UserAccountsEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new UserAccountsEntities object.
        /// </summary>
        public UserAccountsEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "UserAccountsEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Application> Application
        {
            get
            {
                if ((this._Application == null))
                {
                    this._Application = base.CreateQuery<Application>("[Application]");
                }
                return this._Application;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Application> _Application;
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<User> User
        {
            get
            {
                if ((this._User == null))
                {
                    this._User = base.CreateQuery<User>("[User]");
                }
                return this._User;
            }
        }
        private global::System.Data.Objects.ObjectQuery<User> _User;
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        public void AddToApplication(Application application)
        {
            base.AddObject("Application", application);
        }
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    }
    /// <summary>
    /// There are no comments for UserAccountsModel.Application in the schema.
    /// </summary>
    /// <KeyProperties>
    /// LogApplicationId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="UserAccountsModel", Name="Application")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Application : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Application object.
        /// </summary>
        /// <param name="logApplicationId">Initial value of LogApplicationId.</param>
        public static Application CreateApplication(int logApplicationId)
        {
            Application application = new Application();
            application.LogApplicationId = logApplicationId;
            return application;
        }
        /// <summary>
        /// There are no comments for Property LogApplicationId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int LogApplicationId
        {
            get
            {
                return this._LogApplicationId;
            }
            set
            {
                this.OnLogApplicationIdChanging(value);
                this.ReportPropertyChanging("LogApplicationId");
                this._LogApplicationId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("LogApplicationId");
                this.OnLogApplicationIdChanged();
            }
        }
        private int _LogApplicationId;
        partial void OnLogApplicationIdChanging(int value);
        partial void OnLogApplicationIdChanged();
        /// <summary>
        /// There are no comments for Property LogApplicationName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LogApplicationName
        {
            get
            {
                return this._LogApplicationName;
            }
            set
            {
                this.OnLogApplicationNameChanging(value);
                this.ReportPropertyChanging("LogApplicationName");
                this._LogApplicationName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LogApplicationName");
                this.OnLogApplicationNameChanged();
            }
        }
        private string _LogApplicationName;
        partial void OnLogApplicationNameChanging(string value);
        partial void OnLogApplicationNameChanged();
        /// <summary>
        /// There are no comments for Property LogApplicationVersion in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string LogApplicationVersion
        {
            get
            {
                return this._LogApplicationVersion;
            }
            set
            {
                this.OnLogApplicationVersionChanging(value);
                this.ReportPropertyChanging("LogApplicationVersion");
                this._LogApplicationVersion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("LogApplicationVersion");
                this.OnLogApplicationVersionChanged();
            }
        }
        private string _LogApplicationVersion;
        partial void OnLogApplicationVersionChanging(string value);
        partial void OnLogApplicationVersionChanged();
        /// <summary>
        /// There are no comments for User in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("UserAccountsModel", "UserPermission", "User")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<User> User
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<User>("UserAccountsModel.UserPermission", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<User>("UserAccountsModel.UserPermission", "User", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for UserAccountsModel.User in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="UserAccountsModel", Name="User")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class User : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        /// <param name="userId">Initial value of UserId.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="isAdmin">Initial value of IsAdmin.</param>
        public static User CreateUser(string userName, int userId, string password, bool isAdmin)
        {
            User user = new User();
            user.UserName = userName;
            user.UserId = userId;
            user.Password = password;
            user.IsAdmin = isAdmin;
            return user;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this.ReportPropertyChanging("UserName");
                this._UserName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("UserName");
                this.OnUserNameChanged();
            }
        }
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property UserId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId
        {
            get
            {
                return this._UserId;
            }
            set
            {
                this.OnUserIdChanging(value);
                this.ReportPropertyChanging("UserId");
                this._UserId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("UserId");
                this.OnUserIdChanged();
            }
        }
        private int _UserId;
        partial void OnUserIdChanging(int value);
        partial void OnUserIdChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property IsAdmin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin
        {
            get
            {
                return this._IsAdmin;
            }
            set
            {
                this.OnIsAdminChanging(value);
                this.ReportPropertyChanging("IsAdmin");
                this._IsAdmin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsAdmin");
                this.OnIsAdminChanged();
            }
        }
        private bool _IsAdmin;
        partial void OnIsAdminChanging(bool value);
        partial void OnIsAdminChanged();
        /// <summary>
        /// There are no comments for Application in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("UserAccountsModel", "UserPermission", "Application")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Application> Application
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Application>("UserAccountsModel.UserPermission", "Application");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Application>("UserAccountsModel.UserPermission", "Application", value);
                }
            }
        }
    }
}
